name: pull-request
on: [push, pull_request]

jobs:
  # Build job
  build:
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      # - name: Lint
      #   uses: github/super-linter@v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BRANCH: main
      #     VALIDATE_JAVASCRIPT_ES: true
      #     JAVASCRIPT_ES_CONFIG_FILE: ./.eslintrc

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm install
          npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          retention-days: 5
          path: ./build

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artefact
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          token: ${{ github.token }}
